import streamlit as st
st.set_page_config(page_title='Projet Ai', page_icon=':bar_chart:', layout='wide')

st.title("Introduction")
st.subheader("Données de prédiction d'AVC:")
st.write("Selon l'OMS, l'AVC (Accident Vasculaire Cérébral) est la deuxiéme cause de décés dans le monde.Pour prédire si un patient est susceptible de subir un AVC en fonction de paramétres d'entrée (âge, statut tabagique et différentes maladies), on se donne un jeu de données de 2000 lignes et 12 colonnes telles que:")
st.write("**1) identifiant :** identifiant unique (colonne supprimée aprés vérification de l'unicité des identifiants),")
st.write("**2) gender :** <Male>, <Female> ou <Others>,")
st.write("**3) age :** âge du patient,")
st.write("**4) hypertension :** 0 si le patient n'a pas d'hypertension, 1 si le patient a une hypertension,")
st.write("**5) heart_disease :** 0 si le patient n'a pas de maladie cardiaque, 1 si le patient a une maladie cardiaque,")
st.write("**06) ever_married :** <No> ou <Yes>,")
st.write("**7) work_type :** <children>, <Govt_job>, <Never_worked>, <Private> ou <Self_employed>,")
st.write("**8) Residence_type :** <Rural> ou <Urban>,")
st.write("**9) avg_glucose_level :** taux moyen de glucose dans le sang,")
st.write("**10) bmi :** indice de masse corporelle,")
st.write("**11) smoking_status :** <formerly smoked>, <never smoked>, <smokes> ou <Unknown>,")
st.write("**12) stroke :** 1 si le patient a eu un AVC, 0 sinon.Notre cible c'est bien la colonne stroke.")
st.subheader("Remarque:")
st.write("Ajout de 3 colonnes age-interval, age_interval_c et stroke_c qui vont nous être utile pour la visualisation et l'exploration du jeu de données.")